name: ci

on:
  pull_request:
    branches:
    - '**'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.7.0
    with:
     go-version: '1.23'
     go-lint-version: 'v1.60.2'
     install-dependencies-command: 'sudo apt-get install libzmq3-dev'
     run-unit-tests: true
     run-integration-tests: true
     run-lint: true
     run-build: true
     run-gosec: true
     gosec-args: "-no-fail ./..."

  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.10.2
    secrets: inherit
    with:
     publish: false
