name: docker_publish

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.7.0
    with:
     go-version: '1.23'
     go-lint-version: 'v1.60.2'
     install-dependencies-command: 'sudo apt-get install libzmq3-dev'
     run-unit-tests: true
     run-integration-tests: true

  docker_pipeline:
    needs: ["lint_test"]
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.10.2
    secrets: inherit
    with:
     publish: true
     docker_scan: true
    permissions:
        security-events: write
        packages: read
